name: eplhbmodel
channels:
  - pytorch
dependencies:
  - python=3.9
  - pip
  - pytorch
  - torchvision
  - torchaudio
  - pytorch-cuda=12.1
  - numpy
  - scipy
  - scikit-learn
  - matplotlib
  - tqdm
  - ipykernel
  - pip:
    - gitignore_parser